name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to DreamHost
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
        REMOTE_PATH: /home/cmr924/acaexplorers.com/test
        ARGS: '--delete'
